import { useState } from "react";
import API from "../api/api";
import Navbar from "../components/Navbar";
import "../styles/detect.css";

const DetectViolation = () => {
  const [vehicleType, setVehicleType] = useState("");
  const [vehicleNumber, setVehicleNumber] = useState("");
  const [speed, setSpeed] = useState("");
  const [signalJumped, setSignalJumped] = useState(false);
  const [helmetWorn, setHelmetWorn] = useState(false);
  const [result, setResult] = useState(null);

  const submitViolation = async (e) => {
    e.preventDefault();

    try {
      const res = await API.post("/violations/detect", {
        vehicleType,
        vehicleNumber,
        speed,
        signalJumped,
        helmetWorn: vehicleType === "bike" ? helmetWorn : false,
        location: "Main Junction",
      });

      setResult(res.data);
    } catch (err) {
      alert("Violation detection failed");
    }
  };

  // Clean AI report (remove markdown)
  const cleanReport =
    result?.report?.replace(/\*\*/g, "").split("\n").filter((line) => line.trim() !== "");

  return (
    <>
      <Navbar />

      <div className="detect-wrapper">
        <div className="detect-card">
          <h2>AI Traffic Violation Detection</h2>
          <p className="subtitle">
            Enter vehicle details to detect traffic violations using SmartEye AI engine
          </p>

          <form onSubmit={submitViolation}>
            <select
              value={vehicleType}
              onChange={(e) => {
                setVehicleType(e.target.value);
                if (e.target.value !== "bike") {
                  setHelmetWorn(false);
                }
              }}
              required
            >
              <option value="">Select Vehicle Type</option>
              <option value="car">Car</option>
              <option value="bike">Bike</option>
            </select>

            <input
              placeholder="Vehicle Number (MH12AB1234)"
              value={vehicleNumber}
              onChange={(e) => setVehicleNumber(e.target.value)}
              required
            />

            <input
              type="number"
              placeholder="Speed (km/h)"
              value={speed}
              onChange={(e) => setSpeed(e.target.value)}
              required
            />

            <div className="checkbox-row">
              <label>
                <input
                  type="checkbox"
                  checked={signalJumped}
                  onChange={(e) => setSignalJumped(e.target.checked)}
                />
                Signal Jumped
              </label>

              {vehicleType === "bike" && (
                <label>
                  <input
                    type="checkbox"
                    checked={helmetWorn}
                    onChange={(e) => setHelmetWorn(e.target.checked)}
                  />
                  Helmet Worn
                </label>
              )}
            </div>

            <button type="submit">Detect Violation</button>
          </form>

          {result && (
            <div className="result-box">
              <h3>AI Violation Report</h3>

              <p>
                <strong>Violation:</strong> {result.data?.violationType}
              </p>

              <p>
                <strong>Fine:</strong> ₹{result.data?.fineAmount}
              </p>

              <div className="ai-report">
                {cleanReport.map((line, index) => (
                  <p key={index}>{line}</p>
                ))}
              </div>

              <p className="ai-tag">Generated by Gemini AI</p>
            </div>
          )}
        </div>
      </div>
    </>
  );
};

export default DetectViolation;